-- MySQL Script generated by MySQL Workbench
-- qua 24 abr 2019 00:15:40 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema istoe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema istoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `istoe` DEFAULT CHARACTER SET utf8 ;
USE `istoe` ;

-- -----------------------------------------------------
-- Table `istoe`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`ALUNO` (
  `idALUNO` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idUSUARIO` INT NOT NULL,
  PRIMARY KEY (`idALUNO`, `idUSUARIO`),
  INDEX `teste_idx` (`idUSUARIO` ASC),
  CONSTRAINT `fk_usuario_aluno`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `istoe`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`PROFESSOR` (
  `idPROFESSOR` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idUSUARIO` INT NOT NULL,
  PRIMARY KEY (`idPROFESSOR`, `idUSUARIO`),
  INDEX `fk_usuario_professor_idx` (`idUSUARIO` ASC),
  CONSTRAINT `fk_usuario_professor`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `istoe`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`TURMA` (
  `idTURMA` INT NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `unidade` VARCHAR(45) NULL,
  `idPROFESSOR` INT NOT NULL,
  PRIMARY KEY (`idTURMA`, `idPROFESSOR`),
  INDEX `idPROFESSOR_idx` (`idPROFESSOR` ASC),
  CONSTRAINT `fk_professor_turma`
    FOREIGN KEY (`idPROFESSOR`)
    REFERENCES `istoe`.`PROFESSOR` (`idPROFESSOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`EQUIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`EQUIPE` (
  `idEQUIPE` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEQUIPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`JF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`JF` (
  `idJF` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `idTURMA` INT NOT NULL,
  `idEQUIPE` INT NOT NULL,
  `idPROFESSOR` INT NOT NULL,
  PRIMARY KEY (`idJF`, `idTURMA`, `idEQUIPE`, `idPROFESSOR`),
  INDEX `idEQUIPE_idx` (`idEQUIPE` ASC),
  INDEX `idTURMA_idx` (`idTURMA` ASC),
  INDEX `idPROFESSOR_idx` (`idPROFESSOR` ASC),
  CONSTRAINT `fk_turma_jf`
    FOREIGN KEY (`idTURMA`)
    REFERENCES `istoe`.`TURMA` (`idTURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_jf`
    FOREIGN KEY (`idEQUIPE`)
    REFERENCES `istoe`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_jf`
    FOREIGN KEY (`idPROFESSOR`)
    REFERENCES `istoe`.`PROFESSOR` (`idPROFESSOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`FATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`FATO` (
  `idFATO` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(45) NULL,
  `topicoDisciplina` VARCHAR(45) NULL,
  `resposta` VARCHAR(45) NULL,
  `idJF` INT NOT NULL,
  PRIMARY KEY (`idFATO`, `idJF`),
  INDEX `IdJF_idx` (`idJF` ASC),
  CONSTRAINT `fk_jf_fato`
    FOREIGN KEY (`idJF`)
    REFERENCES `istoe`.`JF` (`idJF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`PARTICIPA_EQUIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`PARTICIPA_EQUIPE` (
  `idPARTICIPA_EQUIPE` INT NOT NULL AUTO_INCREMENT,
  `idALUNO` INT NOT NULL,
  `idEQUIPE` INT NOT NULL,
  PRIMARY KEY (`idPARTICIPA_EQUIPE`, `idALUNO`, `idEQUIPE`),
  INDEX `idEQUIPE_idx` (`idEQUIPE` ASC),
  INDEX `idALUNO_idx` (`idALUNO` ASC),
  CONSTRAINT `fk_aluno_participa_equipe`
    FOREIGN KEY (`idALUNO`)
    REFERENCES `istoe`.`ALUNO` (`idALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_participa_equipe`
    FOREIGN KEY (`idEQUIPE`)
    REFERENCES `istoe`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`LIDERA_EQUIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`LIDERA_EQUIPE` (
  `idLIDERA_EQUIPE` INT NOT NULL,
  `idALUNO` INT NOT NULL,
  `idEQUIPE` INT NOT NULL,
  PRIMARY KEY (`idLIDERA_EQUIPE`, `idALUNO`, `idEQUIPE`),
  INDEX `idALUNO_idx` (`idALUNO` ASC),
  INDEX `idEQUIPE_idx` (`idEQUIPE` ASC),
  CONSTRAINT `fk_aluno_lidera_equipe`
    FOREIGN KEY (`idALUNO`)
    REFERENCES `istoe`.`ALUNO` (`idALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_lidera_equipe`
    FOREIGN KEY (`idEQUIPE`)
    REFERENCES `istoe`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`MATRICULADO_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`MATRICULADO_TURMA` (
  `idMATRICULA_TURMA` INT NOT NULL,
  `idALUNO` INT NOT NULL,
  `idTURMA` INT NOT NULL,
  PRIMARY KEY (`idMATRICULA_TURMA`, `idALUNO`, `idTURMA`),
  INDEX `idTURMA_idx` (`idTURMA` ASC),
  INDEX `idALUNO_idx` (`idALUNO` ASC),
  CONSTRAINT `fk_aluno_matriculado_turma`
    FOREIGN KEY (`idALUNO`)
    REFERENCES `istoe`.`ALUNO` (`idALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_matriculado_turma`
    FOREIGN KEY (`idTURMA`)
    REFERENCES `istoe`.`TURMA` (`idTURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istoe`.`RESPONDE_FATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `istoe`.`RESPONDE_FATO` (
  `idRESPONDE_FATO` INT NOT NULL AUTO_INCREMENT,
  `idFATO` INT NOT NULL,
  `idALUNO` INT NOT NULL,
  PRIMARY KEY (`idRESPONDE_FATO`, `idFATO`, `idALUNO`),
  INDEX `IdALUNO_idx` (`idALUNO` ASC),
  INDEX `IdFATO_idx` (`idFATO` ASC),
  CONSTRAINT `fk_fato_responde_fato`
    FOREIGN KEY (`idFATO`)
    REFERENCES `istoe`.`FATO` (`idFATO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_response_fato`
    FOREIGN KEY (`idALUNO`)
    REFERENCES `istoe`.`ALUNO` (`idALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
